### ISSUE TITLE
Help->About correction + Why I get build failed on simple working Hello World smart contract

### ISSUE THREAD

**Issue by swdevMPaul** [NeoParticle/NeoStudio#1]
Hi,

Thank you for your development. Nice work.

Please correct / resolve next:

1) In the current version when user opens Help->About window the window title is "NEO Studo", but should be "NEO Studio" (i is missing), you may correct this in code.

2) When I create new simple Hello World smart contract, there are no errors apear and select "Build" I get build failed. Why ?

Kind Regards.

**Comment by NeoParticle** [comment]
Hi, Thanks for your response!!!

Actually I created this while trying to program smart contract and test on NEO. It was very hard to switch between development and testing. And also felt it would be nice if we can debug on real time testnet.
For now the tool uses neon compiler from environment path variable and also neo certificate has to be installed in the same PC. Installing certificate and bringing the neon compiler inside is in my future proposal/idea. For now to insatall certificate plz use neo-gui once. And for neon.exe please use neo source and do a build, then add the path to environment variable. 
https://github.com/neo-project/neo-compiler
http://docs.neo.org/en-us/sc/getting-started-csharp.html
